use_frameworks!

target 'RxTheme_Example' do
	platform :ios, '9.0'
	pod 'RxTheme', :path => '../'
end

target 'RxTheme_Example_tvOS' do
	platform :tvos, '9.0'
	pod 'RxTheme', :path => '../'
end

target 'RxTheme_Example_macOS' do
	platform :osx, '10.10'
	pod 'RxTheme', :path => '../'
end

target 'RxTheme_Example_watchOS Extension' do
	platform :watchos, '3.0'
	pod 'RxTheme', :path => '../'
end

target 'RxTheme_Tests' do
	platform :ios, '9.0'
	pod 'RxTheme', :path => '../'
end
